version: "3.7"
services:

  goodback-dev-mongo:
    image: mongo:4.2
    container_name: goodback-dev-mongo
    ports:
      - "6645:27017"
    expose:
      - "6645"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: on-failure
    networks:
      - goodback-dev-mongo-network
    volumes:
      - ./mondodb_data:/data/db

  goodback-dev-mongo-ui:
    container_name: goodback-dev-mongo-ui
    image: mongo-express
    restart: on-failure
    depends_on:
      - goodback-dev-mongo
    ports:
      - "6644:8081"
    expose:
      - "6644"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: goodback-dev-mongo
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_SITE_BASEURL: /dbview
    networks:
      - goodback-dev-mongo-network

networks:
  goodback-dev-mongo-network:
    driver: bridge